### PR TITLE
Fix container types calculation

### LINKED ISSUE #150: Improve container types calculation
An `AstNode` instance has an optional field `$container`, which presents its container -- a parental `AstNode`. The feature makes casting an `AstNode` to its container pretty comfortable, however it works nicely exclusively, when there is the only one possible container for the `AstNode`. Current questions:

- How the case of multiple container types will be used?
- How to improve multiple container types calculation?

**The problem of multiple container types calculation**
There are types `A`, `B` and `C`, and `C` extends `A` and `B`.  If now we add a type `D`, containing a field with a type `A`, `A` will get a container `D`. Also we add a type `E`, containing a field with a type `B`, and `B` gets a container `E`. These manipulations make `C` invalid -- what is the `C`'s container type?

**The current solution**
Share container types of parents. For the example above: the container type of `A` will become `D | E`, and the container type of `B` will become `D | E`, so the container type of `C` will be determined: `D | E`.

**Problems of the solution**
1. Number of container types can grow very fast. Suppose, we add a type `F`, which extends our type `B` and one more type `G`. To have consistent `F`, we have to share container types of `G` with `A` and `B` and add `D | E` to `G`'s container types.
2. Container types become senseless. Container types of `G` can be senseless for types `A` and `B`.

### PR DESCRIPTION
**Pull request by pluralia**
Closes #150.
* drops union types from the calculation of container types
* drops sharing of container types over connected components: now the container types are lifted only lifted to the parents
* if one of the children has no container types, the parent also loses container types

Examples:
```
interface A extends AstNode { $container: E | F | G; strA: string }
interface B extends AstNode { $container: E | F | H; strB: string }
interface C extends A, B { $container: E; strC: string }
interface D extends A, B { $container: F; strC: string }
interface E extends AstNode{ c: C }
interface F extends AstNode{ d: D }
interface G extends AstNode{ a: A }
interface H extends AstNode{ b: B }
```

`X` has no container types -- `A` and `B`, too
```
interface A extends AstNode { strA: string }
interface B extends AstNode { strB: string }
interface C extends A, B { $container: E; strC: string }
interface D extends A, B { $container: F; strC: string }
interface X extends A, B { strC: string }
interface E extends AstNode{ c: C }
interface F extends AstNode{ d: D }
interface G extends AstNode{ a: A }
interface H extends AstNode{ b: B }
```

### CODE REVIEW

File: packages/langium/src/grammar/generated/ast.ts [hunk 1]
```diff
@@ -418,7 +411,7 @@ export function isGroup(item: unknown): item is Group {
 }
 
 export interface Keyword extends AbstractElement {
-    readonly $container: Alternatives | Assignment | CharacterRange | CrossReference | Grammar | Group | NegatedToken | ParserRule | TerminalAlternatives | TerminalGroup | TerminalRule | UnorderedGroup | UntilToken;
+    readonly $container: CharacterRange;
```
Comment (spoenemann) [inline packages/langium/src/grammar/generated/ast.ts:414]: This looks wrong: CharacterRange is not the only possible container of Keyword.

**Review by spoenemann — COMMENTED** [review]
Thanks, it looks mostly good (found only one wrongly computed container in the grammar).

File: packages/langium/src/grammar/generated/ast.ts (hunk 1 above)
Comment (pluralia) [reply packages/langium/src/grammar/generated/ast.ts:414]: @spoenemann, it's correctly for the current calculation:
* `Keyword` is used in the assignment in the only one place -- in `CharacterRange`
* One more usage is the rule `PredicatedKeyword` that infers `Keyword` -- 1) the interface `PredicatedKeyword` will not be generated by the grammar definition, so no its income to container types; 2) if we would have the interface `PredicatedKeyword`, it would be a child of `Keyword` -- no income to container type, too, because we don't lift children container types in parents anymore
* Other usages are in type alternatives and are ignored by the new algorithm: `AssignableTerminal`, `CrossRefTerminal`, `AbstractTerminal`

Comment (spoenemann) [reply packages/langium/src/grammar/generated/ast.ts:414]: There's a rather complex chain of unassigned rule calls here:

Alternatives > ConditionalBranch > UnorderedGroup > Group > AbstractToken > AbstractTokenWithCardinality > AbstractTerminal > Keyword

Alternatives has two possible containers: Group and ParserRule. Keyword should inherit those containers.

I've seen that in simpler examples of unassigned rule calls, the container types are fine. So maybe this is just a special case for which we can create an issue, but we ignore it for now?

Comment (pluralia) [reply packages/langium/src/grammar/generated/ast.ts:414]: By my understanding it's not an issue, but an expected behaviour for the current algorithm.

The moment is the algorithm is working with inferred / declared types (from the `ast.ts`, basically) and not with parser rules content. That means, not all information that you can see in the `.langium` is available for the algorithm. As a result:
1. Most of types with the names from the chain doesn't exist
2. `Group` and `ParserRule` contain only `AbstractElement` and not `Alternatives`

**Review by spoenemann — APPROVED** [review]
Thanks!

File: packages/langium/src/grammar/generated/ast.ts (hunk 1 above)
Comment (spoenemann) [reply packages/langium/src/grammar/generated/ast.ts:414]: Ok let's ignore the issue for now and get back to it in case it turns out to be a real problem. I created #1063 so we don't forget.
