### PR TITLE
Extract string patterns for textmate grammar

### LINKED ISSUE #281: Two slashes inside a string detected as a comment
Langium version: 0.2.0-next.1f60202

## Steps To Reproduce

Screenshot 2021-11-01 at 15 27 44

## The current behavior
Text inside string turns to comment after slashes

## The expected behavior
Text inside string doesn't turn to comment after slashes

### PR DESCRIPTION
**Pull request by msujew**
Closes #281

Extracts string patterns from the grammar to generate the textmate grammar. The issue only occurred because there was no string pattern in the textmate grammar in the first place, which would've prevented the keyword/comment pattern to be highlighted.

### CODE REVIEW

File: packages/langium-cli/src/generator/textmate-generator.ts [hunk 1]
```diff
@@ -132,3 +133,33 @@ function getKeywordSymbols(grammar: langium.Grammar, pack: LangiumConfig): Patte
     };
 }
 
+function getStringPatterns(grammar: langium.Grammar, pack: LangiumConfig): Pattern[] {
+    const terminals = langium.stream(grammar.rules).filter(langium.isTerminalRule);
+    const stringTerminal = terminals.find(e => e.name.toLowerCase() === 'string');
+    const strinPatterns: Pattern[] = [];
```
Comment (spoenemann) [inline packages/langium-cli/src/generator/textmate-generator.ts:139]: Nitpick: `stringPatterns`

**Review by spoenemann — APPROVED** [review]
Thanks!
