### PR TITLE
Catch errors during module resolution

### LINKED ISSUE #463: Add error handling in dependency injection impl
If
```javascript
value(injector)
```

of
https://github.com/langium/langium/blob/bc75d2866559224e96d632b50585624f1dffd803/packages/langium/src/dependency-injection.ts#L86

in
https://github.com/langium/langium/blob/bc75d2866559224e96d632b50585624f1dffd803/packages/langium/src/dependency-injection.ts#L83-L87

fails, `obj[prop] === __requested__` holds afterwards, and in a subsequent attempt the following error is thrown, which can be quite misleading:
https://github.com/langium/langium/blob/bc75d2866559224e96d632b50585624f1dffd803/packages/langium/src/dependency-injection.ts#L79-L81

I suggest to replace
https://github.com/langium/langium/blob/bc75d2866559224e96d632b50585624f1dffd803/packages/langium/src/dependency-injection.ts#L86

by
```javascript
    try {
        obj[prop] = (typeof value === 'function') ? value(injector) : _inject(value, injector);
    } catch (error) {
        obj[prop] = undefined;
        console.error(error);
        throw error;
    }
```

### PR DESCRIPTION
**Pull request by Lotes**
@sailingKieler I copy-pasted your solution.

Closes #463

Remark: the affected file is really hard to read.

### CODE REVIEW

**Comment by sailingKieler** [comment]
LGTM
@Lotes did you try out implementation by letting some services crash on purpose during the initialization, e.g. the name provider in the domain model example: https://github.com/langium/langium/blob/2392ddd9854aca45047a459c85a3cf9eb61e24bd/examples/domainmodel/src/language-server/domain-model-module.ts#L22-L34

**Comment by Lotes** [comment]
Yes. I added some crashes by throwing errors.

**Review by sailingKieler — APPROVED** [review]
Fine for me

**Comment by Lotes** [comment]
@sailingKieler Sorry. But I realized that there is a way to test this scenario. In the case of an error, I am saving the error for the after service. If then some other service is requesting it in a follow-up call, we get a "construction failure" where the cause is the saved error.

File: packages/langium/src/dependency-injection.ts [hunk 1]
```diff
@@ -76,14 +76,22 @@ const __requested__ = Symbol();
...
         }
         return obj[prop];
     } else if (prop in module) {
         const value: Module<I, T[keyof T]> | ((injector: I) => T[keyof T]) = module[prop as keyof T];
         obj[prop] = __requested__;
-        obj[prop] = (typeof value === 'function') ? value(injector) : _inject(value, injector);
+        try {
+            obj[prop] = (typeof value === 'function') ? value(injector) : _inject(value, injector);
+        } catch (error) {
+            obj[prop] = error;
```
Comment (spoenemann) [inline packages/langium/src/dependency-injection.ts:92]: Please add an `instanceof Error` check here as well (theoretically you can throw anything in JS).

Comment (Lotes) [reply packages/langium/src/dependency-injection.ts]: ok

**Review by spoenemann — APPROVED** [review]

File: packages/langium/test/dependency-injection.test.ts [hunk 2]
```diff
@@ -59,7 +59,7 @@ describe('A non-cyclic dependency', () => {
     });
 
     test('should be result on an idempotent api call', () => {
-        const api = inject({ dep: () => ({ }) });
+        const api = inject({ dep: () => ({}) });
         expect(api.dep).toBe(api.dep);
```
Comment (sailingKieler) [inline packages/langium/test/dependency-injection.test.ts:63]: This is a tautology, isn't it? Does that make any sense?

File: packages/langium/src/dependency-injection.ts [hunk 3]
```diff
@@ -76,14 +76,22 @@ const __requested__ = Symbol();
...
         return obj[prop];
     } else if (prop in module) {
         const value: Module<I, T[keyof T]> | ((injector: I) => T[keyof T]) = module[prop as keyof T];
         obj[prop] = __requested__;
-        obj[prop] = (typeof value === 'function') ? value(injector) : _inject(value, injector);
+        try {
+            obj[prop] = (typeof value === 'function') ? value(injector) : _inject(value, injector);
+        } catch (error) {
+            obj[prop] = error instanceof Error ? error : undefined;
+            throw error;
```
Comment (sailingKieler) [inline packages/langium/src/dependency-injection.ts:93]: With this solution the "Construction failure."-Message would be thrown on the subsequent attempt after a previous failure, right?

Why not just:
```suggestion
            obj[prop] =  undefined;
            if (error instanceof Error)
                throw new Error('Construction failure. Please make sure that your dependencies are constructable.', {cause: obj[prop]});
            else
                throw error;
```

File: packages/langium/test/dependency-injection.test.ts (hunk 2 above)
Comment (Lotes) [reply packages/langium/test/dependency-injection.test.ts:63]: I think it is meant as: two subsequent calls, return the same result.

File: packages/langium/src/dependency-injection.ts (hunk 3 above)
Comment (Lotes) [reply packages/langium/src/dependency-injection.ts:93]: Exactly! Imagine you would throw the original one: You would have the old stack trace, not the new one. It is another trace leading to this construction attempt.
Do you think there is a better option?

File: packages/langium/test/dependency-injection.test.ts (hunk 2 above)
Comment (sailingKieler) [reply packages/langium/test/dependency-injection.test.ts:63]: At the first glance I expected a test expression like
```
expect(api.dep()).toBe(api.dep());
```
... i.e. `api.dep()` instead of `api.dep`.

I overlooked the fact that `api` is the proxy object created by `inject(...)`, and that the supplier function `dep` is called internally once the property `dep` is requested ... what this PR is more or less about ... my bad!
